#!/bin/bash

sxhkd -c $HOME/.config/berry/sxhkdrc &
pulseaudio --start
exec picom &

feh --no-startup-id feh --bg-fill -Z /home/aya/Downloads/wallhaven-45kjv5_1920x1080.png &
$HOME/.config/polybar/launch.sh

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       38
berryc edge_gap           50 10 10 10

# Set decoration colors
berryc focus_color         a71e10
berryc unfocus_color       7ea6b0
berryc inner_focus_color   a71e10
berryc inner_unfocus_color 7ea6b0
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"
